[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "chromatix"
authors = [{name = "Chromatix Team"}]
description = "Differentiable wave optics library using JAX"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "jax[cpu,cuda12]>=0.4.6",
    "einops >= 0.6.0",
    "flax >= 0.6.3",
    "chex>=0.1.86",
    "optax >=0.1.4",
    "scipy >= 1.10.0",
    "typing-extensions >=4.12",
    "matplotlib>=3.9.2",
    "pytest>=8.3.3",
    "ruff>=0.7.1",
    "jaxopt>=0.8.3",
    "ipykernel>=6.29.5",
    "optimistix>=0.0.9",
]
version = "0.3.0"

[project.optional-dependencies]
dev = ["pyright>=1.1.366", "pytest>=7.2.0", "ruff >= 0.4.8"]
docs = ["mkdocs >= 1.4.2", "mkdocs-material >= 9.0.6", "mkdocstrings-python >= 0.8.3", "mkdocs-jupyter"]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
ignore = ["E402"]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]


[tool.pyright]
include = ["src/"]
ignore = ["src/chromatix/data"]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
